apiVersion: v1
kind: Service
metadata:
  name: bannerv2-service
spec:
  type: NodePort
  selector:
    app: bannerv2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  # or whatever port your Go app serves on

